### ISSUE TITLE
Bug: Unhandled GC for RouterViews

### ISSUE THREAD

**Issue by 7kayoh** [frappedevs/FusionRouter#1]
RouterView uses `Fusion.Value` to display the current view, when switching to a new page, the `Component` (basically the view) in `self.CurrentRoute` will be called `:set()` with the new page, `Fusion.Value` does not GC the value inside the state when removed, only unparented. This leads to huge problem in the future and should be solved in FusionRouter

**Comment by bubbabiga** [comment]
There is no unhandled GC, once the state's value changes, the previous value will no longer have any references and will be collected in the next GC cycle (assuming it is a reference-type).

Here's some quick code to understand this:

```
local state = {
    value = {}
}

local weakTable = setmetatable({state.value}, {__mode = "v"})
state.value = {} -- set the state's value to a new one, the old value will now no longer have refs and will be gced in the next gc cyle

while weakTable[1] do
     task.wait(1)
end

warn("Old vaue gced")
```

Additionally, Fusion doesn't implement a `Destroy` method for state objects but ideally you should make sure that the state object no longer has unneeded **strong** references once it is no longer under use, especially the value set to it (if any).
